services:
  fast_api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    volumes:
      - .:/app
    command: /start
    ports:
      - 8080:8000
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    hostname: db
    networks:
      - backend
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    restart: always
    image: redis:7.2.5-alpine
    networks:
      - backend
    expose:
      - 6379

  test_db:
    restart: always
    image: postgres:16.3-alpine
    volumes:
      - test_postgres_data:/var/lib/postgresql/data/
    hostname: test_db
    expose:
      - 5431
    networks:
      - backend
    environment:
      - POSTGRES_DB=${TEST_POSTGRES_DB}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}

volumes:
  postgres_data:
  test_postgres_data:

networks:
  backend:
    driver: bridge
