"""empty message

Revision ID: 1c56a922c8b0
Revises: 782c8c47fcbd
Create Date: 2025-05-24 15:37:07.243041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c56a922c8b0"
down_revision: Union[str, None] = "782c8c47fcbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "redirecturls", ["url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "redirecturls", type_="unique")
    # ### end Alembic commands ###
