"""empty message

Revision ID: 782c8c47fcbd
Revises: 6cd5d1823e11
Create Date: 2025-05-24 15:07:15.227988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "782c8c47fcbd"
down_revision: Union[str, None] = "6cd5d1823e11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_redirecturls_url"), table_name="redirecturls")
    op.create_index(op.f("ix_redirecturls_id"), "redirecturls", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_redirecturls_id"), table_name="redirecturls")
    op.create_index(op.f("ix_redirecturls_url"), "redirecturls", ["url"], unique=False)
    # ### end Alembic commands ###
